### ISSUE TITLE
Temporary Update for Post v0.1.22 Changes

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Installer#110]
I have a few changes I want to make in demo-tasks.  However, it looks like updating past v0.1.22 will require some extra changes in Super.Human.Installer (#99).   I'll plan to manually copy these changes if we get stuck on v0.1.22:

https://github.com/STARTcloud/hcl_roles/issues/1
https://github.com/STARTcloud/hcl_roles/issues/2
https://github.com/STARTcloud/hcl_roles/issues/3

**Comment by JoelProminic** [comment]
@Aszusz, I made another update (on the `development` branch) to fix the Windows scripts.   I confirmed that the updates do not break the actions on macOS.  Please test this on Windows when you have a chance.

**Comment by Aszusz** [comment]
I created new build and tested on Windows. It seems to fail much later in the process (but still complains about backslashes). It also prints insanely large log to the Moonshine IDE console. Attaching the log.
[conversion-log.txt](https://github.com/Moonshine-IDE/Super.Human.Installer/files/14195216/conversion-log.txt)

**Comment by JoelProminic** [comment]
The lengthy log is because the Maven build is doing some initial setup for the project.

The ZIP message is just a warning - my code update properly detects the error code for this case and continues the action, so this seems to be working properly.  I could redirect STDERR for this command so that it doesn't show up in the error ouptut.

The actual error looks like a permission issue:

    : [ERROR] Failed to execute goal org.openntf.maven:nsfodp-maven-plugin:3.8.1:generate-metadata (default-generate-metadata) on project nsf-moonshine-domino: Execution default-generate-metadata of goal org.openntf.maven:nsfodp-maven-plugin:3.8.1:generate-metadata failed: java.nio.file.AccessDeniedException: /tmp/nsfodp/20240207082422/nsfs/nsf-moonshine/odp/Code/Java/demo -> [Help 1]

**Comment by JoelProminic** [comment]
@Aszusz, if you haven't already, please check the ownership on these files.  Both the owner and group should be `java_user`:

    ls -lh /tmp/nsfodp/20240207082422/nsfs/nsf-moonshine/odp/Code/Java/demo

This should have been fixed by [this line](https://github.com/Moonshine-IDE/Super.Human.Installer/blob/d44df2e75b491ddbfd7bf9b9d7f70fa16a7f9203/Assets/provisioners/demo-tasks/0.1.20/scripts/ansible/roles/domino_updatesite/templates/run_nsfodp.sh.j2#L36).  We confirmed that the line looks like this:

    java_user@dev-1201:/opt/domino/scripts$ grep "chown" /opt/nsfodp/run_nsfodp.sh 
    sudo chown -R java_user:java_user .

If you continue having problems, please send me a copy of your zipped project, and I'll do more testing with this.   If you want to try to test the script yourself, you can run:

    sudo su - java_user
    bash
    /opt/nsfodp/run_nsfodp.sh /tmp/restinterface/upload/2FD6B26F-7EA2-EDB4-B9A9-83F48204A978.zip


You also mentioned some agent errors. If you did not successfully deploy the database in the above step, that could explain the error.  You can debug the database access like this:

    sudo su - java_user
    bash
    java -jar CheckDatabase.jar mars/planets PieChartNsf.nsf

If you are still having errors, please send me the errors.

**Comment by JoelProminic** [comment]
I made some further tweaks to the above scripts:
- use `java_group` insertion parameter
- use insertion parameters for domino user and group
- Added `2>&1` to unzip command so that warning is displayed as part of the normal output rather than as a separate error.

I wouldn't expect any of these changes to affect the behavior of the script significantly, though.  @Aszusz, let me know if you continue having errors.

FYI, @piotrzarzycki21 reported that I should switch back to the master branch.  I noticed that master didn't have the changes from my previous commit, but it looks like the development branch is removed now.   I committed the scripts to master.

**Comment by JoelProminic** [comment]
I also pushed some updates for the other pending issues.
- Added import_json_documents.sh script and capabilities
- Updated REST API capabilities.  The other file updates are not visible through the REST API yet - I need to make updates on the REST API itself next.

**Comment by JoelProminic** [comment]
The provisioner updates are done, but I need to make an update to the REST Interface to return the [new properties](https://github.com/STARTcloud/hcl_roles/issues/1). This doesn't necessarily need to block a release.

**Comment by JoelProminic** [comment]
We are planning an 0.9.0 release tomorrow, so I'll revisit the REST-Interface updates later.
