### ISSUE TITLE
Create full cloud build and release process

### ISSUE THREAD

**Issue by Aszusz** [Moonshine-IDE/Super.Human.Installer#2]
Things to be done:

---
Building binary:
- [x] Linux
- [x] Windows
- [x] MacOS
---
Creating installers:
- [x] Linux
- [x] Windows
- [x] MacOS
---
Signing:
- [x] Windows
- [x] MacOS
- [x] MacOS notarization
---
Release process:
- [x] Draft release
- [x] Version info
---
Miscellaneous:
- [x] Chocolatey package

**Comment by Igazine** [comment]
@Aszusz 

Starting from version 0.8.13 (it's in a separate branch, not merged yet into development), the following updates will be required in the build actions:

- [Champaign](https://github.com/Moonshine-IDE/Champaign.git) should be added as a new haxelib dependency
- - `haxelib git champaign https://github.com/Moonshine-IDE/Champaign.git`

Please do not make this change just yet, it's just a heads-up for the upcoming changes.
Thank you
