### ISSUE TITLE
Cannot launch webpage on Windows

### ISSUE THREAD

**Issue by Aszusz** [Moonshine-IDE/Super.Human.Installer#37]
The vagrant process seems to finish successfully and the server is provisioned, but I cannot launch the webpage to test

```
This server has been provisioned with DemoTasks Roles v0.1.17
https://github.com/DominoVagrant/demo-tasks/releases/tag/v0.1.17
[SHI]: 'vagrant up' stopped with exit code: 0
[SHI]: Invalid web address: %1
[SHI]: Invalid web address: [null]
```

OS is Windows 10 x64.
Attaching the full log (from 2nd run): 
[vagrant-log-cannot-launch-webpage.txt](https://github.com/Moonshine-IDE/Super.Human.Installer/files/10567917/vagrant-log-cannot-launch-webpage.txt)

I'm going to destroy the server and retest.

**Comment by Igazine** [comment]
No need to destroy for now.

Please attach the following files from the server's local directory:

```
{serverdir}/.vagrant/done.txt
{serverdir}/.vagrant/provisioned-briged-ip.txt
```

Thank you

**Comment by Aszusz** [comment]
Attaching the files

[done.txt](https://github.com/Moonshine-IDE/Super.Human.Installer/files/10568943/done.txt)
[provisioned-briged-ip.txt](https://github.com/Moonshine-IDE/Super.Human.Installer/files/10568944/provisioned-briged-ip.txt)
