### ISSUE TITLE
Core/UI: Enable 'Open Vagrant SSH' button during 'up' if it can be launched

### ISSUE THREAD

**Issue by Igazine** [Moonshine-IDE/Super.Human.Installer#47]
Enable 'Open Vagrant SSH' button during 'up' if it can be launched.
Check against the relevant finished task in vagrant log, and enable the button accordingly

**Comment by JoelProminic** [comment]
Discussing this today, accessing the instance with `vagrant ssh` while it is provisioning should be possible, but it probably won't add much value over connecting after provisioning as failed.   This could also end up breaking provisioning if the user starts making changes.  I don't think we need this anymore, but we can reopen it if we change our minds.
