### ISSUE TITLE
Core: Execute 'vagrant halt' for provisioned servers if 'vagrant up' is unsuccessful

### ISSUE THREAD

**Issue by Igazine** [Moonshine-IDE/Super.Human.Installer#53]
Execute 'vagrant halt' for provisioned servers if 'vagrant up' is unsuccessful

**Comment by JoelProminic** [comment]
As discussed during the meeting today, this issue may cause some trouble for @MarkProminic and me when debugging issues with the Vagrant scripts.  If we want to SSH to the VM to check what went wrong, we will need to start the VM again:
- If we run `vagrant up`, this could change the state
- We could manually start the VirtualBox VM, but this would not account for any applications started

Another concern I have is that we could lock someone out of their test server if a non-critical provisioner fails.  On the other hand, if the server didn't start perfectly, the user could see and report unexpected errors.

I think it would be good to add an "Advanced" flag to disable the functionality from this issue.  I'll create a separate issue for this.

By my understanding Tamas added this to avoid issues with the Vagrant state not matching the state in SHI after an error. We may want a separate state to cover this case, but we can revisit this after some more practical testing.

I'm tagging @JustinProminic in case he has more thoughts on this.
