### ISSUE TITLE
Flag to Disable "Cleanup" Logic for Failed Provisioning

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Installer#56]
As discussed during the meeting today, I would like to see a flag to disable the cleanup logic for #50 and #53.  See the comments I added to the issues for some context for why this would be needed.

**Comment by Igazine** [comment]
A new toggle has been added to the Settings page, the cleanup logic can be turned off.
v0.8.11 Development is available to download to test from the regular channels
