### ISSUE TITLE
Install superhumanportal with Genesis

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Installer#68]
We would like to install the `superhumanportal` addin with Genesis.  This should be as simple as adding `superhumanportal` [here](https://github.com/DominoVagrant/demo-tasks/blob/9315d44a40a129f03050aaf6f8151a4dd9c55047/ansible/roles/domino_genesis_applications/defaults/main.yml#LL4C15-L4C15).

However, there are a couple issues complicating this:
- We can't update easily to the next v0.1.18 version of `demo-tasks`, since there are supporting changes required for Super.Human.Installer
- From what I remember, there is a local copy of `demo-tasks` in this repository that should be updated instead.

**Comment by JoelProminic** [comment]
I think this is the corresponding file in Super.Human.Installer:  https://github.com/Moonshine-IDE/Super.Human.Installer/blob/68b74310c9f8dc91c224ebb9e416680c51dd2bb8/Assets/provisioners/demo-tasks/0.1.15/scripts/ansible/roles/domino-genesis-applications/defaults/main.yml#L4

Note that this would be overwritten the next time we want to update from `demo-tasks`, but it should be sufficient for a quick fix.

**Comment by JoelProminic** [comment]
Updated.  Note that my previous comment linked to the 0.1.15 version, but there is a separate 0.1.17 file:  https://github.com/Moonshine-IDE/Super.Human.Installer/blob/d77bd0f6cff4fe76fb3386129431f785bd8f4850/Assets/provisioners/demo-tasks/0.1.17/scripts/ansible/roles/domino-genesis-applications/defaults/main.yml#L5

I'll plan to run a fresh test when I have a chance.

**Comment by piotrzarzycki21** [comment]
@JoelProminic How can I check if superhumanportal is installed ?

**Comment by piotrzarzycki21** [comment]
@Aszusz released development version of Super Human Installer [0.8.15-dev](https://github.com/Moonshine-IDE/Super.Human.Installer/releases/tag/0.8.15-dev). I have installed server using it on my Mac OS Ventura 13.3.1(a). Unfortunately I don't see that superhumanportal was installed along with it - I was simply checking url, but maybe there is a way of check whether portal is installed trough SSH console ?

**Comment by JoelProminic** [comment]
Testing this build on macOS Monterey, I confirmed that I can access Super.Human.Portal through the URL.  We can debug this on your VM in the meeting tomorrow.  Watch that you are using js-release build:  https://domino.%server%/Super.Human.Portal/js-release/index.html
