### ISSUE TITLE
Add CHANGELOG for 0.8.15

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Super.Human.Installer#71]
CHANGELOG for 0.8.15 -> https://github.com/Moonshine-IDE/Super.Human.Installer/blob/development/CHANGELOG.md#super-human-installer-0815

**Comment by piotrzarzycki21** [comment]
@JoelProminic if you could quickly review.

**Comment by JoelProminic** [comment]
I reviewed the file and made some updates on the development branch.
