### ISSUE TITLE
Unable to remove servers

### ISSUE THREAD

**Issue by SurJames** [Moonshine-IDE/Super.Human.Installer#74]
**Describe the bug**
After uninstalling both the Dev and Production of versions 0.8.15, and removing the files/folders from User / AppData/Local, and then reinstalling 0.8.15, the previous Domino server instances show up in the new install. The server does not appear in VirtualBox.

**To Reproduce**
3. See error

**Expected behavior**
I expected an empty server pages

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 1.0.0]
Windows 11 Pro

**Additional context**
Please attach the crash log (crash.txt) or paste its contents here

**Comment by SurJames** [comment]
Update - also found files/folders under User/AppData/Roaming as well. This was bringing back the deleted servers after the uninstall / reinstall. 
Now back to a clean startup.

**Comment by SurJames** [comment]
Also, after an uninstall, the production version still leaves the Users / James/AppData/Roaming/SuperHumanInstaller folder with logs and server in place.

**Comment by piotrzarzycki21** [comment]
@SurJames I have pushed changes where you should have possibility to remove server when you end up in that state. Newest development build have these changes - if you prefer using production version we will soon release it. Let me know if it address above issue. 

Dev build: https://github.com/Moonshine-IDE/Super.Human.Installer/releases/tag/0.8.18-dev

**Comment by SurJames** [comment]
Hello Pieter

Very nice delete function I like the two step process - destroy 
configuration and then delete completely. Nicely Done.

I did notice that it did leave the setting in VirtualBox as Inaccesible, 
but that is an easy one. 

Overall excellent fix. Greatly Appreciated.

Thank You

Jim

Jim Anderson
Anderson Technical Services, Inc.
Website: www.AndersonTechs.com
Ph: 610-291-5340 (c)
***@***.***






From:   "Piotr Zarzycki" ***@***.***>
To:     "Moonshine-IDE/Super.Human.Installer" 
***@***.***>
Cc:     "SurJames" ***@***.***>, "Mention" 
***@***.***>
Date:   07/14/2023 07:08 AM
Subject:        Re: [Moonshine-IDE/Super.Human.Installer] Unable to remove 
servers (Issue #74)



@SurJames I have pushed changes where you should have possibility to 
remove server when you end up in that state. Newest development build have 
these changes - if you prefer using production version we will soon 
release it. Let me know if it address above issue.
Dev build: 
https://github.com/Moonshine-IDE/Super.Human.Installer/releases/tag/0.8.18-dev
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: 
***@***.***>
