### ISSUE TITLE
Crash when you using nomad-server-1.0.8

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Super.Human.Installer#75]
Mode details on this bug soon...

**Comment by piotrzarzycki21** [comment]
I have fixed crash itself - it shouldn't happen anymore. I will create another issue to get to the bottom whether SHI tried to install nomad-server-0.1.8 or it's just a hardcoded message in logs. I'm attaching logs here, but this will be part of the next issue as well. 

[shi_logs.zip](https://github.com/Moonshine-IDE/Super.Human.Installer/files/11883072/shi_logs.zip)

[console_log.txt](https://github.com/Moonshine-IDE/Super.Human.Installer/files/11883076/console_log.txt)

@JustinProminic please test development build https://github.com/Moonshine-IDE/Super.Human.Installer/releases/tag/0.8.16-dev

**Comment by JoelProminic** [comment]
We discussed the Nomad 0.1.8 error today.  I created a separate issue for this, since it is a more generic problem:  #76 

We can focus this issue on avoiding the crash for this case.

**Comment by piotrzarzycki21** [comment]
We have got information that newest SHI didn't crash for Justin. Issue has been fixed.
