### ISSUE TITLE
Placeholder Interface for Service Type

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Installer#88]
As a placeholder for the interface updates in #84, we would like to add a new "Service Type" interface when creating a new server.  This will be useful for @JustinProminic when doing a demo:

When the user clicks Create New, they should see an interface like this:
![image](https://github.com/Moonshine-IDE/Super.Human.Installer/assets/24532731/f389cd8e-ec10-4f55-aefe-a5e95f24e025)

    Standalone Domino Server, A new, independent Domino Server
    Additional Domino Server, Additional server based on an existing organization
    Volt MX, Not yet implemented

Only the "Standalone Domino Server" entry should be usable for now.  When the user selects this, they should see the current interface:
![image](https://github.com/Moonshine-IDE/Super.Human.Installer/assets/24532731/c3f072a2-c22b-4141-ab7c-e6b371720ca8)

**Comment by piotrzarzycki21** [comment]
@JoelProminic I just pushed implementation of this view to development. Please test it while you will have chance. 
- One additional update which has to be done is that non implemented entry shouldn't be clickable - I will add that tomorrow

Artifacts should be updated here in about 20 min:  https://github.com/Moonshine-IDE/Super.Human.Installer/releases/tag/0.8.19-dev

**Comment by JoelProminic** [comment]
![image](https://github.com/Moonshine-IDE/Super.Human.Installer/assets/24532731/e5baa5d8-763b-4ba6-aa3a-8b3c4c0e9799)

I see that Continue takes me to the original form regardless of which entry I select, which works for now.  

Otherwise, this is looking good.  I'm tagging @JustinProminic in case he wants to review it.

**Comment by piotrzarzycki21** [comment]
> Please revise the wording as follows:
> 
> 1. Standalone Domino Server instead of just "Standalone Domino"
> 2. Additional server based upon an existing configuration is not a correct description.  It should instead be "Join a new server to an existing Domino environment"
> 3. Volt MX should be "Volt MX Go Foundry Server"
> 4. "Not yet implemented" should be "Coming soon!"
> 
> Thank you!

@JustinProminic Text has been adjusted. New development build is ready. You need to install it manually on your sight.

**Comment by piotrzarzycki21** [comment]
I have made an update to make sure that hover and selection on other rows is disabled. There is one issue which I cannot overcome - when I click on different row first row loosing it's selection - only visual, because behind the stage selectedIndex remains unchanged. - I don't won't to spend time on that issue - if it's possible. 

https://github.com/Moonshine-IDE/Super.Human.Installer/releases/tag/0.8.19-dev

**Comment by piotrzarzycki21** [comment]
Placeholder of service type screen has been added.
